-- What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as revenue
from customer
group by gender




-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied="Yes" and purchase_amount>(select avg(purchase_amount) from customer)



-- Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),3) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5



-- Compare the average purchase amounts between Standard and Express Shipping.
 select shipping_type,round(avg(purchase_amount),3) as average_revenue
 from customer
 where shipping_type="Standard" or shipping_type="Express"
 group by shipping_type




-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,round(avg(purchase_amount),3) as average_spend, sum(purchase_amount) as revenue
from customer
group by subscription_status
order by average_spend,revenue



-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased as product,round(sum(case when discount_applied="Yes" then 1 else 0 end)/count(*),3)  as percentage
from customer
group by item_purchased
order by percentage desc
limit 5



-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
with previous_customer as (select customer_id,
							case when previous_purchases=1 then "New"
								 when previous_purchases between 2 and 10 then "Returning"
								 else "Loyal" end as segment
							from customer
				)
select segment,count(customer_id) as cnt
from previous_customer
group by segment





-- What are the top 3 most purchased products within each category?
select item_purchased as product,category,total
from
(select item_purchased,category,count(*) as total,
rank() over ( partition by category order by count(*) desc) as rnk
from customer
group by item_purchased,category) as r
where rnk>=3



-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(*) as cnt
from customer
where previous_purchases>=5
group by subscription_status






-- What is the revenue contribution of each age group?
select age_group ,sum(purchase_amount) as revenue
from customer
group by age_group









